/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comp603;

import javax.swing.JOptionPane;

/**
 *
 * @author GGPC
 */

//check if user has enough money let person in or show error/dont do anything
public class CasinoPanel extends javax.swing.JFrame {

    Controller controller;
    /**
     * Creates new form BackPanel
     */
    public CasinoPanel(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BBlack = new javax.swing.JButton();
        BLook = new javax.swing.JButton();
        BRules = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Casino of New Zealand");

        BBlack.setText("BlackJack");
        BBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBlackActionPerformed(evt);
            }
        });

        BLook.setText("Look Around");
        BLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLookActionPerformed(evt);
            }
        });

        BRules.setText("Rules");
        BRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRulesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(BBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(BLook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addComponent(BRules))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BRules)
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLookActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Goodbye");
        System.exit(0);
    }//GEN-LAST:event_BLookActionPerformed

    private void BRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRulesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Your goal in blackjack is to beat the dealer’s hand without going over 21. You’ll receive 2 cards at the beginning of each round, and you’ll add up the values of these cards."
                + "\nCards 2-10 have face value; King, Queen, Jack are worth 10; and Aces are either a 1 or an 11 — it’s up to you to decide. "
                + "\nThe dealer also draws two cards. The aim of the game is to beat his hand (have a higher hand) without going over 21. "
                + "\nIf you would like the dealer to deal you another card, you tell him “hit” If you do not want to be dealt another card, you “stand” “Busting” is when the sum of your hand is over 21. "
                + "\nThe winner of the round is whoever has the highest hand without going bust.");
        
        
    }//GEN-LAST:event_BRulesActionPerformed

    private void BBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBlackActionPerformed
        // TODO add your handling code here:
        //check if user has money
        //b
        this.controller.gui.BJPanel.setVisible(true); //switch screen
        this.setVisible(false); //hide login panel
    }//GEN-LAST:event_BBlackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBlack;
    private javax.swing.JButton BLook;
    private javax.swing.JButton BRules;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
